import { Inter } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./Smooth/SmoothScroll";
import ClientProvider from './ClientProvider'; // Import the ClientProvider


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>

          {/*<SmoothScroll>
            
          </SmoothScroll>*/}
          {children}
          </ClientProvider>

      </body>
    </html>
  );
}
